export enum CORE_KEYWORDS {
  MONSTER = 'MONSTER',
  CHARACTER = 'CHARACTER',
  EPIC_HERO = 'EPIC HERO',
  PSYKER = 'PSYKER',
  INFANTRY = 'INFANTRY',
  FLY = 'FLY',
  BEAST = 'BEAST',
  SWARM = 'SWARM',
  AIRCRAFT = 'AIRCRAFT',
  TRANSPORT = 'TRANSPORT',
  DEDICATED_TRANSPORT = 'DEDICATED TRANSPORT'
}

export enum CORE_ABILITIES {
  SCOUTS_8 = 'Scouts 8"',
  LEADER = 'Leader',
  FIGHTS_FIRST = 'Fights First',
  INFILTRATORS = 'Infiltrators',
  LONE_OPERATIVE = 'Lone Operative',
  STEALTH = 'Stealth',
  DEADLY_DEMISE_1 = 'Deadly Demise 1',
  DEADLY_DEMISE_D3 = 'Deadly Demise D3',
  DEADLY_DEMISE_D6 = 'Deadly Demise D6',
  FEEL_NO_PAIN_5 = 'Feel No Pain 5+',
  DEEP_STRIKE = 'Deep Strike',
  HOVER = 'Hover'
}

export enum WEAPON_ABILITIES {
  ASSAULT = 'ASSAULT',
  RAPID_FIRE = 'RAPID FIRE',
  IGNORES_COVER = 'IGNORES COVER',
  TWIN_LINKED = 'TWIN-LINKED',
  PISTOL = 'PISTOL',
  PSYCHIC = 'PSYCHIC',
  TORRENT = 'TORRENT',
  LETHAL_HITS = 'LETHAL HITS',
  LANCE = 'LANCE',
  INDIRECT_FIRE = 'INDIRECT FIRE',
  PRECISION = 'PRECISION',
  BLAST = 'BLAST',
  MELTA = 'MELTA',
  HAZARDOUS = 'HAZARDOUS',
  DEVASTATING_WOUNDS = 'DEVASTATING WOUNDS',
  SUSTAINED_HITS = 'SUSTAINED HITS',
  EXTRA_ATTACKS = 'EXTRA ATTACKS',
  HEAVY = 'HEAVY'
}

export const STATSBLOCK = {
  move: 0,
  toughness: 0,
  save: 0,
  wounds: 0,
  leadership: 0,
  objectiveControl: 0,
  abilities: {}
};
