export enum CORE_KEYWORDS {
  MONSTER = 'MONSTER',
  CHARACTER = 'CHARACTER',
  EPIC_HERO = 'EPIC HERO',
  PSYKER = 'PSYKER',
  INFANTRY = 'INFANTRY',
  FLY = 'FLY',
  BEAST = 'BEAST',
  SWARM = 'SWARM',
  AIRCRAFT = 'AIRCRAFT',
  TRANSPORT = 'TRANSPORT',
  DEDICATED_TRANSPORT = 'DEDICATED TRANSPORT'
}

export enum WEAPON_ABILITIES {
  ASSAULT = 'ASSAULT',
  RAPID_FIRE = 'RAPID FIRE',
  IGNORES_COVER = 'IGNORES COVER',
  TWIN_LINKED = 'TWIN-LINKED',
  PISTOL = 'PISTOL',
  PSYCHIC = 'PSYCHIC',
  TORRENT = 'TORRENT',
  LETHAL_HITS = 'LETHAL HITS',
  LANCE = 'LANCE',
  INDIRECT_FIRE = 'INDIRECT FIRE',
  PRECISION = 'PRECISION',
  BLAST = 'BLAST',
  MELTA = 'MELTA',
  HAZARDOUS = 'HAZARDOUS',
  DEVASTATING_WOUNDS = 'DEVASTATING WOUNDS',
  SUSTAINED_HITS = 'SUSTAINED HITS',
  EXTRA_ATTACKS = 'EXTRA ATTACKS',
  HEAVY = 'HEAVY'
}

export const STATSBLOCK = {
  move: 0,
  toughness: 0,
  save: 0,
  wounds: 0,
  leadership: 0,
  objectiveControl: 0,
  abilities: {}
};
